.catalog:
  name: "Wordpress"
  version: "5.2.0-201605-GA"
  description: "An elegant, well-architectured personal publishing system"
  uuid: wordpress-5.2-201605-1
  minimum_rancher_version: v0.56.0
