name: Wordpress
description: |
  Wordpress is the largest self-hosted blogging tool in the world, used on millions of sites and seen by tens of millions of people every day.
version: 0.1
category: "Blogtool"
